Add support for Yes/No/Cancel buttons
PolyMeilex/rfd pull request #123
Opened 2023-06-13 18:35 UTC by Adanos020

Fixes #81 

I based this off of this fork: https://github.com/zphixon/rfd

The Yes/No/Cancel provided by the OS seem to work fine on Linux and macOS, however:
- Didn't compile on Windows,
- There was no support for custom text in the 3 buttons.

I addressed both of these issues and updated the documentation of `MessageDialog` accordingly.

Tested on Windows and Linux (GTK3).

WASM, macOS and Linux (XDG) need testing.

2023-06-13 18:35 UTC, Adanos020 commented
Opening this again because I accidentally closed #122

2023-06-28 10:49 UTC, PolyMeilex requested changes
Sorry for the delay, this looks great, just one minor comment.

2023-06-28 10:49 UTC, PolyMeilex commented on src/message_dialog.rs
> +#[derive(Debug, Default)]
```suggestion
#[derive(Debug, Default, Clone, PartialEq, Eq)]
```
Just to make it easier to use in if statements without pattern matching

2023-06-29 09:00 UTC, anhosh commented on src/message_dialog.rs
> +#[derive(Debug, Default)]
Done! Also made one more minor change

2023-07-06 21:01 UTC, PolyMeilex commented
Thanks!

2023-07-06 21:01 UTC, merged